### ISSUE TITLE
Refactor: 코드 리팩토링 (+출발지 설정 로직 구현)

### ISSUE THREAD

**Issue by speardragon** [HanieumNodeServer/HanieumNodeServer#40]
### description

전반적인 코드의 흐름이 localhost에 http 통신을 하여 이어지던 이전의 코드 방식에서 
내부 함수를 만들어 해당 함수를 호출하여 이어지는 식으로 리팩토링을 진행하였다.
(by 멘토님과의 회의-2022.07.29)

### Problem 

아무리 localhost에 http 통신으로 접근하는 것일지라도 결국은 http 통신이기 때문에 서버 내부에서 코드가 돌아가는 것이 아니라 바깥으로 빠지기 때문에 코드의 흐름이 번잡하고 시간 또한 더 걸릴 수밖에 없다는 문제를 지적 받았다.
또한 데이터 베이스에 query문을 날릴 때 또한 for문을 통해서 여러번(수백번?) 날리게 되면 굉장히 안 좋기 때문에 한 번에 원하는 모든 데이터를 가져올 수 있는 쿼리문을 작성하여 한 번의 쿼리로 가져올 수 있도록 해야 했다.

### work flow

- [x] function 폴더에 bus.js 파일을 통해 원하는 함수 작성
- [x] 근처에 있는 버스 터미널을 검색하는 controller에서 가장 큰 터미널을 찾는 로직에 대한 함수 구현
- [x]  AI로부터 받는 키워드 중에 도착지만 있는 경우에 대한 API에서 현재 위치로부터 해당 도착지로 갈 수 있는 터미널 중 가장 가까운 터미널을 찾는 함수 구현
- [x] 위와 동일한 API에서 출발지와 도착지 ID를 인자로 받아 배차를 가져오는 함수 구현
- [x] AI로부터 받는 키워드 중에 도착지+출발지가 있는 경우에 대한 API
  - [x] 출발 키워드를 포함하는 모든 터미널에 대해 각각마다 도착 가능한 터미널 리스트를 만드는 함수 구현
  - [x]  도착 키워드를 포함하는 모든 터미널에 대해 각각마다 출발 가능한 터미널 리스트를 만드는 함수 구현
  - [x] 터미널 리스트를 인자로 받아 해당 터미널 중에 가장 규모가 큰 터미널을 찾는 함수 구현 

### TODO
함수에서 에러가 발생하는 validation을 undefined로 임시방편 처리하였는데 이에 대한 처리 방안을 모색해야 함.

### break change
function 디렉토리 생성 및 bus 관련 함수 작성
